name: Upload To Azure Blob Storage
on: workflow_dispatch
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: qmbase
          container_name: public-joy-ride
          connection_string: ${{ secrets.ConnectionString }}
          sync: false
